### ISSUE TITLE
Segment fault on Debian when listing archive files with Chinese characters

### ISSUE THREAD

**Issue by YaxinCheng** [OSSystems/compress-tools-rs#100]
Segment fault happens on Debian when `list_archive_files` or `list_archive_files_with_encoding` is called for archives whose files contain Chinese characters.

**The two functions work fine on macOS when listing files with or without Chinese characters.**

Error message:
```
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

I realized the problem when I put my binary into docker. I don't have a Debian environment except docker, so the reproduce steps are using docker. Sorry about that.

Reproduce:
1. Unzip [compress_tools_test.zip](https://github.com/OSSystems/compress-tools-rs/files/10369168/compress_tools_test.zip)
2. `docker build . -t compress-tools-test`
3. `docker run --rm -it --entrypoint sh compress-tools-test`
4. `cargo run`

The zip used for the test is included in the zip above, but if you want to download it separately, here it is: [test.zip](https://github.com/OSSystems/compress-tools-rs/files/10369174/test.zip)

**Comment by otavio** [comment]
Could you try to create a small test case in the form of a PR so we can have something to use as a base?

**Comment by YaxinCheng** [comment]
Test case added in PR #101

**Comment by otavio** [comment]
The error is because the Docker image lacks a default locale. Use:
```sh
LC_ALL=C.UTF-8 cargo test
```
However #103 address the segfault. Now it error out.
