### ISSUE TITLE
Questions about some choices

### ISSUE THREAD

**Issue by YaxinCheng** [OSSystems/compress-tools-rs#104]
I am reading the code, but have questions about some function choices, hoping that you can help me with.

1. Why `archive_read_open` instead of `archive_read_open_filename`? The second one seems much easier, and it handles the file reading and seeking for you. It simplifies the code as you don't need to create `SeekableReadPipe` etc.
2. Is there some reason on setting the value `READER_BUFFER_SIZE` to 16384? Or it is just some radom value that works great? 

Thanks for your time

**Comment by otavio** [comment]
The choice of `archive_read_open_filename` was made as we work on buffers and anything that provides a `Read` trait. We don't operate on files exclusively.

The buffer size has been chosen as smaller possible, which supports all use cases we test. We need to use a small buffer as we also use the crate in embedded Linux devices, so we need to be conservative in memory use.

**Comment by YaxinCheng** [comment]
That makes sense. Thanks for the explanation!
