### ISSUE TITLE
Proper way to include your code in my library?

### ISSUE THREAD

**Issue by YaxinCheng** [OSSystems/compress-tools-rs#105]
Hi, I am building a similar library (inspired by yours but crafted to my own needs), and I am using one of your file [locale.rs](https://github.com/OSSystems/compress-tools-rs/blob/master/src/ffi/locale.rs). 

I am wondering:
1. If I can include the file in my library (using MIT License)
2. I did not make change to the file, which includes the Copyright comments. Is this enough? I have following lines at the beginning of the file: 
```
//
// This file is taken from https://github.com/OSSystems/compress-tools-rs/blob/master/src/ffi/locale.rs
// All the credit goes to https://github.com/OSSystems
//
// Copyright (C) 2021 O.S. Systems Software LTDA
//
// SPDX-License-Identifier: MIT OR Apache-2.0
// ...
```

Please let me know. If this is inappropriate, I apologize and I will delete the file

**Comment by otavio** [comment]
It is totally fine to reuse the file. Why couldn't we work together and avoid duplicated work?  What is missing in this crate?

**Comment by YaxinCheng** [comment]
Hey thanks for allowing me to reuse the code first of all. 

In compress-tools, the file content is read by blocks into a `Write`. It only finishes when all the blocks are read or an error happens. In my use case, I want to return each block when after reading it, and I want to be able adjust the block size. 

It's a pretty edgy case, so I don't think it's worthwhile to refactor compress-tools to support it. I have tried to add the functionality to compress-tool directly, but it requires a lot of work to breakdown the current structure of `run_with_archive`. The function releases the resource when it's done, so we have to read all blocks before the function ends.

Overall, thanks for your great work on this library! My library will mostly serve my own edgy use cases, and I would definitely come to compress-tools for the most common scenarios.
