### ISSUE TITLE
Bundle libarchive

### ISSUE THREAD

**Issue by basicfunc** [OSSystems/compress-tools-rs#118]
Hey, there it would be great if `bundled` feature would be added to library so that it can compile `libarchive` itself as many `rusqlite` project does.

**Comment by otavio** [comment]
Thanks for your suggestion! We think it's a great idea and we're definitely open to accepting a pull request that adds this support.

**Comment by basicfunc** [comment]
Okay, I’ll try to figure it out until then I’m closing this issue
