### ISSUE TITLE
Feature request: List files in an archive

### ISSUE THREAD

**Issue by Aloso** [OSSystems/compress-tools-rs#22]
I'd like to use this crate to show comic book archives in [emulsion](https://github.com/ArturKovacs/emulsion). To do this, I need to iterate over all the files in an archive. Would it be possible to add a function that returns all file names in the archive?

**Comment by Jonathas-Conceicao** [comment]
@Aloso I think it can easily be done. It's an useful feature we have been thinking about adding as well. @Asakiz, will get to it soon.

**Comment by Aloso** [comment]
Thanks a lot!

**Comment by Asakiz** [comment]
Sorry for the delay, but I have good news.
We added a function to list all files in a machine, called `list_files`.
Also add documentation and modify the example to show the new feature.

**Comment by otavio** [comment]
@Aloso, I'll move this discussion to the PR #23 so we keep it focused there.

**Comment by otavio** [comment]
@Aloso could you give the `master` branch a try? As we changed the MSRV we will do a breaking release but I'd like you to give it a try prior we make a release.

**Comment by Aloso** [comment]
Yes, I will. But I have to sleep first, it's already 3 a.m. where I live :)
