### ISSUE TITLE
Windows Pkg-Config

### ISSUE THREAD

**Issue by a8nJ** [OSSystems/compress-tools-rs#38]
I see currently that VcPkg is required with Windows:

https://github.com/OSSystems/compress-tools-rs/blob/6e6efc8b25887fadf0dcfa3a97110a83c8163743/src/build.rs#L13-L18

I think this is not ideal, as Visual Studio is not the only Windows development
environment. In fact, Windows users can also utilize Pkg-Config:

https://packages.msys2.org/package/mingw-w64-x86_64-pkg-config

**Comment by otavio** [comment]
Sure; would you like to provide a PR to improve it?

We are not Windows users so if someone who knows it better can contribute, it'd be good.

**Comment by a8nJ** [comment]
https://github.com/OSSystems/compress-tools-rs/pull/39

**Comment by a8nJ** [comment]
Done, forgot the Readme though, so if this is acceptable we might need to revise that as well
