### ISSUE TITLE
Error using `uncompress_archive_file` on 7zip archive

### ISSUE THREAD

**Issue by hohav** [OSSystems/compress-tools-rs#46]
I'm getting this error when trying to extract a single file from a 7zip archive:
```
Error: Extraction("Current client reader does not support seeking a device")
```
That message originates from libarchive. There's a possibly-related [issue](https://github.com/libarchive/libarchive/issues/1292) on their tracker, but I tried patching seek capability into `archive_read_open_FILE` with no change.

I tried inspecting the `compress-tools` source, but couldn't identify the libarchive code path that triggers this error. Until I know that, I can't formulate a proper bug report for libarchive. Any guidance would be appreciated.

**Comment by otavio** [comment]
Is there an archive we can use to reproduce the issue?

**Comment by hohav** [comment]
Github wouldn't let me upload a 7z, so I had to make a repo:

https://github.com/hohav/7zip-test/blob/master/foo.7z

**Comment by otavio** [comment]
@hohav we reproduced this. @Asakiz is looking at this issue.

**Comment by otavio** [comment]
@hohav we fixed the issue. Could you give this a try and confirm it works fine for you?

**Comment by hohav** [comment]
Works now. Thank you!
