### ISSUE TITLE
Cannot build on Windows, link.exe exits with error code 1102

### ISSUE THREAD

**Issue by atlanticaccent** [OSSystems/compress-tools-rs#47]
Hi,

First off thanks for this crate.

So far I have the minimal example compiling under WSL2, but the same code fails to build with the following note:

`= note:    Creating library C:\Users\wanty\Documents\ssmm_rust\target\debug\deps\StarsectorModManager.lib and object C:\Users\wanty\Documents\ssmm_rust\target\debug\deps\StarsectorModManager.exp
          archive.lib(filter_fork_windows.c.obj) : error LNK2019: unresolved external symbol __imp_WaitForInputIdle referenced in function __archive_create_child
          libcrypto.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetProcessWindowStation referenced in function OPENSSL_isservice
          libcrypto.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_GetUserObjectInformationW referenced in function OPENSSL_isservice
          libcrypto.lib(cryptlib.obj) : error LNK2019: unresolved external symbol __imp_MessageBoxW referenced in function OPENSSL_showfatal
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_list_certs
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function capi_find_key
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function capi_find_cert
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFindCertificateInStore referenced in function capi_find_cert
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertDuplicateCertificateContext referenced in function capi_load_ssl_client_cert
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function capi_dsa_free
          libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertGetCertificateContextProperty referenced in function capi_cert_get_fname
          C:\Users\wanty\Documents\ssmm_rust\target\debug\deps\StarsectorModManager.exe : fatal error LNK1120: 11 unresolved externals`

I have libarchive installed using vcpkg, using the triplet x86_64-windows-static-md.

I'm not sure if there's an issue surrounding how I've installed libarchive or something between that and trying to build my project.

If there's any other information you need please do let me know.

**Comment by otavio** [comment]
Hello, we faced this issue in past and it seems that the openssl fail to static link. See https://github.com/OSSystems/compress-tools-rs/commit/c3463d9f16b982b284beb1a5d0542ecc679292c6

**Comment by atlanticaccent** [comment]
Great, I look forward to the release. Is there an expected date for it?

**Comment by otavio** [comment]
The fix was just on CI. So if you do the same at your end it should work.

**Comment by otavio** [comment]
As we had no feedback, we'll assume it worked, I am closing this issue then.

**Comment by atlanticaccent** [comment]
Sorry to resurrect an old thread, but I'm now running into this issue again when attempting to run static compiles on Windows. I understand if that's not something that can be easily fixed though.
I do have compilation working under dynamic linking however.

**Comment by otavio** [comment]
Please open a specific issue about static linking on Windows. So we can track this individually.
