### ISSUE TITLE
Failed to decompress compressed files (tar.gz, zip) on Windows

### ISSUE THREAD

**Issue by innobead** [OSSystems/compress-tools-rs#50]
When using `uncompress_archive`, it works well on Linux platforms but failed with the below error on Windows.

```rust
use compress_tools::{uncompress_archive, Ownership};
uncompress_archive(&download_file, &extract_dir, Ownership::Ignore)?;
```

Error: Extraction error: 'INTERNAL ERROR: Function 'archive_write_data_block' invoked with archive structure in state 'header', should be in state 'data''

**Comment by otavio** [comment]
Do you have a test case?

**Comment by innobead** [comment]
You can follow the below steps to reproduce.

1. install vs 2019 community build toolset (ref: https://github.com/microsoft/vcpkg#quick-start-windows)
2. vcpkg install libarchive
```console
vcpkg integrate install
vcpkg install libarchive:x64-windows-static-md
```
3. Download https://github.com/nakabonne/ali/releases/download/v0.5.4/ali_0.5.4_windows_amd64.tar.gz
4. then have a code to uncompress the tar.gz.
```console
let extract_dir = env::current_dir()?;
let download_file = File::open(&download_file_path)?;
info!("Decompressing {:?} to {:?}", &download_file, &extract_dir);
uncompress_archive(&download_file, &extract_dir, Ownership::Ignore)?;
```

**Comment by otavio** [comment]
@innobead I tried to reproduce the issue using our CI, and I couldn't. I tried:

- using 2020.11-1 vcpkg release
- using the tip of vcpkg repo

For the archives, I tried both the `ali` tarball and the `tree.tar.gz` from the integration tests. I ended reworking the integration tests, so it runs on Windows as well.

I don't have a Windows desktop to try it myself now. I tried Azure but, for some weird reason, it failed to validate my phone. Could you try to add a test on the integration test which shows the issue?

**Comment by innobead** [comment]
@otavio thanks for the prompt reply and even enhanced the test pipeline!

After some investigation, it works well now. I found the root cause is the download file path is the prefix of the dest folder like <download-file-path>/<dest dir>. 

BTW, good work for this library :+1:
