### ISSUE TITLE
UTF8Error when listing or uncompressing zip archive with utf-8 filename

### ISSUE THREAD

**Issue by thallada** [OSSystems/compress-tools-rs#59]
I tried extracting this archive on Ubuntu 20.04.1 with both the apt libarchive-dev and manually compiled latest libarchive 3.5.1:

[test.zip](https://github.com/OSSystems/compress-tools-rs/files/6826189/test.zip)

```rust
use compress_tools::list_archive_files;
use std::fs::File;

fn main() {
    let file = File::open("test.zip").unwrap();
    for file_name in list_archive_files(&file).unwrap() {
        dbg!(&file_name);
    }
}
```
This returns:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf(Utf8Error { valid_up_to: 0, error_len: Some(1) })', src/main.rs:6:48
```

I tried a couple of the latest revisions of this library but it still fails on every one.

Output of `locale`:
```
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Unfortunately, I'm getting a separate linking error trying to install compress-tools on Windows so I'm unable to test on that platform.

**Comment by otavio** [comment]
I could reproduce the issue but I am unsure what are the expected symbols? Which tool does unpack it successfully?

**Comment by thallada** [comment]
Pretty sure this is the expected filename: 
![Screenshot 2021-07-15 220446](https://user-images.githubusercontent.com/1505923/125880587-72109136-6595-42fb-a544-29637f9689dd.png)

I tried both 7zip and WinRAR and both show a garbled filename:
![Screenshot 2021-07-15 220657](https://user-images.githubusercontent.com/1505923/125880737-844e4531-0753-4487-9494-8463a1b147e0.png)

So it's possible this archive is screwed up somehow. However I'm able to extract with those garbled filenames with both tools. I would prefer the messed up filenames to the entire process crashing. For my usecase, I don't really care about the filenames, I just need the bytes of the uncompressed files. Even if I don't care about that file in particular, the whole `list_archive_files` call errors out.

**Comment by otavio** [comment]
It does indeed. What language and encoding is this?

**Comment by otavio** [comment]
I found where we were failing to decode the filenames and changed it to use _lossy_ strings. Now it'll not fail if invalid filenames are used.

I'll send a PR and mark this issue. Please do a test at your side.

**Comment by thallada** [comment]
Awesome, thank you for the very fast response!

I tested listing and uncompressing the test.zip archive with your PR and it succeeded without crashing. The filename came out as `���_�ҏW�ȈՃw���v.jpg`, but like I mentioned that's acceptable for me.

To be honest, I don't know what the original encoding of that file was. I only know that the original name was japanese characters (`頂点編集簡易ヘルプ.jpg`) because the server it was uploaded to shows metadata for the archive and lists every file in it with apparently the correct encoding. The zip file was uploaded by someone else to a server and perhaps the encoding got screwed up somewhere in the process of upload -> CDN -> download. I'm not very knowledgeable about encodings.
