### ISSUE TITLE
Zip-slip vulnerability

### ISSUE THREAD

**Issue by awused** [OSSystems/compress-tools-rs#63]
`uncompress_archive` is vulnerable to [zip-slip](https://github.com/snyk/zip-slip-vulnerability).

This can be verified with the test files in https://github.com/snyk/zip-slip-vulnerability/tree/master/archives. Using [zip-slip.zip](https://github.com/snyk/zip-slip-vulnerability/blob/master/archives/zip-slip.zip) I was able to extract `good.txt` to my chosen directory but `evil.txt` was extracted to `/tmp/`.

This is usually worthy of  security advisory.

**Comment by otavio** [comment]
@awused, are you willing to look at this vulnerability?

It'd be nice to fix it before the next release.

**Comment by awused** [comment]
I don't use the vulnerable methods and I'm not looking to become a maintainer of this project. You could look into getting a CVE number for this, it is pretty serious, and it shouldn't just be a "nice to fix."
