### ISSUE TITLE
Iterate archive without reading all data.

### ISSUE THREAD

**Issue by Morganamilo** [OSSystems/compress-tools-rs#72]
The current archive iterator reads through all data in the archive when I'm only interested in very little of it.

It would be nice if each new file returned an iterator that you could optionally iterate to get the data.

**Comment by otavio** [comment]
Can you explain more about the use case?

**Comment by Morganamilo** [comment]
So I have to call ` list_archive_files` which will iterate through it and give me a file list. Then find the files I want, Then call `uncompress_archive_file` n times?

This mean's if I extract 10 tiles I'd end up iterating through the archive 11 times.

**Comment by Morganamilo** [comment]
So reading how libarchive works it would seem the function `archive_read_data_skip()` just reads and discards the data which mean's the whole thing will be read either way. So I guess this feature is not really possible. (unless archive_read_data_skip, does optimise and just skip the data).

It still would be nice to have the iterator have all the header data and not just the filename but that's a separate issue.

**Comment by otavio** [comment]
Have you, @Morganamilo, designed something on this direction?

**Comment by Morganamilo** [comment]
I'm here again as I'm doing stuff with this crate again and hit the same need for this.

I see #109 but what I really wanted was just a `next_header()` function on the ArchiveIterator to skip as I wish.

When I opened this issue my use case was reading only specific files that matched a regex which #109 covers.

This time I want to just read through all the file names. Either all or until I find the one I need. I see `list_archive_files` but it doesn't really fit as I have tens of thousands of files and want to stream them.

**Comment by otavio** [comment]
Please check if you can prepare a purchase request and we can discuss the API next.
