### ISSUE TITLE
Entry information

### ISSUE THREAD

**Issue by TethysSvensson** [OSSystems/compress-tools-rs#75]
It would be nice to be able to get information about entries, e.g. file type or the creation time.

**Comment by otavio** [comment]
Great. Do you have an idea for the API?

**Comment by Jonathas-Conceicao** [comment]
Libarchive does provide a [few functions](https://manpages.debian.org/testing/libarchive-dev/archive_entry_stat.3.en.html) for getting information about entries. A think they would generally come in hand when iterating over them in the API we currently provide.

It would need some internal code change, but I think it would be useful to have them accesable as methods over the `iterator::ArchiveContents`.

**Comment by TethysSvensson** [comment]
I've implemented a hack to support my usecase here: https://github.com/TethysSvensson/compress-tools-rs/commit/d52e0fd4082d26ce86f8847290651aa4239a8c1a

**Comment by otavio** [comment]
@TethysSvensson, the proposed API isn't bad. I think the stat could use a Rust type for it. Did you improve it?

**Comment by TethysSvensson** [comment]
@otavio No, I'm still using my branch from November.

**Comment by otavio** [comment]
Please rebase and prepare a PR.

**Comment by otavio** [comment]
@TethysSvensson, https://docs.rs/nix/latest/nix/sys/stat/struct.FileStat.html could be an option.

**Comment by otavio** [comment]
Once you prepare an initial PR, I'll try to rework it.

**Comment by TethysSvensson** [comment]
> @TethysSvensson, https://docs.rs/nix/latest/nix/sys/stat/struct.FileStat.html could be an option.

The `FileStat` struct in the nix crate is simply a re-export of the `stat` struct from the `libc` crate.

**Comment by otavio** [comment]
Fixed in f654d6d.
