### ISSUE TITLE
7z uncompress_archive_file fail

### ISSUE THREAD

**Issue by pkptzx** [OSSystems/compress-tools-rs#78]
When I process 7z files, some 7z files will have errors, but if I use the command to decompression, it is normal. 

thread 'main' panicked at 'Failed to get the file: Extraction("Truncated 7-Zip file body")' 

```
let written = uncompress_archive_file(&mut source, &mut target, "tree/branch2/leaf")
        .expect("Failed to get the file");
```

**Comment by otavio** [comment]
Do you have a simple test case?

**Comment by otavio** [comment]
I didn't receive feedback since January, so I am closing it. Feel free to ask for a reopening if this still happens.
