### ISSUE TITLE
uncompress 7z failed in new libarchive version 13.5.2

### ISSUE THREAD

**Issue by pkptzx** [OSSystems/compress-tools-rs#79]
uncompress 7z failed in new libarchive version 13.5.2

`panicked at 'Extraction("LZMA codec is unsupported")'`

old libarchive version 13.3.3 it's ok.

**Comment by pkptzx** [comment]
os: centos 8

**Comment by otavio** [comment]
This seems the library has been built with the lzma disabled.

**Comment by pkptzx** [comment]
> Could you confirm? I'd like to close this.

OK
