### ISSUE TITLE
sub-directories as file names

### ISSUE THREAD

**Issue by sonnenscheinchen** [OSSystems/compress-tools-rs#89]
compress-tools v0.13.0, libarchive v3.6.1

Example archive:
http://ftp.uni-erlangen.de/mirrors/aminet/demo/aga/Hardcore.lha

Test:
```
use compress_tools::*;
use std::fs::File;
use std::path::Path;

fn main() -> Result<()> {
    let mut source = File::open("Hardcore.lha")?;
    let dest = Path::new("/tmp/dest");
    uncompress_archive(&mut source, dest, Ownership::Ignore)?;
    Ok(())
}

```
Current result:
File "035.SDM" in root directory named "sdm-hardcore\datas\035.SDM"
```
$ ls /tmp/dest/
 File_Id.Diz   Hardcore.readme   sdm-hardcore  'sdm-hardcore\datas\035.SDM'
```

Expected result:
File "035.SDM" in directory "sdm-hardcore/datas"
```
$ ls /tmp/dest/
 File_Id.Diz   Hardcore.readme   sdm-hardcore  
```

**Comment by otavio** [comment]
Was this working before 0.12.4 release?

**Comment by otavio** [comment]
Ok, so I did few tests:

1. reproduced using 0.12.3 release
2. reproduced using 0.13.0 release
3. checked it works using `bsdtar`

So this is indeed a issue with this create. Now, we need to find why.

**Comment by sonnenscheinchen** [comment]
Found another one:
http://ftp.uni-erlangen.de/mirrors/aminet/demo/aga/FLP-TTD.lha

I tested with 7z, lha (lhasa),the delharc crate and various gui apps using libarchive. Everything is fine. It is strange that only some files fail in this particular way and not all. A mystery. :-)

**Comment by otavio** [comment]
Not a mistery, it has different path separator. See:
```
[src/lib.rs:259] target_path = "t/sdm-hardcore/datas/034.SDM"
[src/lib.rs:259] target_path = "t/sdm-hardcore\\datas\\035.SDM"
[src/lib.rs:259] target_path = "t/sdm-hardcore/datas/036.SDM"
```

**Comment by otavio** [comment]
I am trying to understand why it isn't splitting the `Components`.

**Comment by otavio** [comment]
I got the debug output using following patch:
```diff
diff --git a/src/lib.rs b/src/lib.rs
index 0db45a9..6978a0b 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -254,7 +254,9 @@ where
                     .to_str()
                     .unwrap(),
                 )
-                .unwrap();
+                    .unwrap();
+
+                dbg!(&target_path);
 
                 ffi::archive_entry_set_pathname(entry, target_path.as_ptr());
 ```

**Comment by otavio** [comment]
It seems the core issue is the Path handling in Rust. See following example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a2dc0880eb9be5b30156b9d206cd0d1b

**Comment by sonnenscheinchen** [comment]
> Not a mistery, it has different path separator.

Hm, then the problem is somewhere else (earlier?) because every path in the archive is separated by a single backslash.
See:
```
$ strings Hardcore.lha | grep datas

[...]
sdm-hardcore\datas\034.SDM
sdm-hardcore\datas\035.SDM     <---- this!
sdm-hardcore\datas\036.SDM
[...]

```
Still a mystery. :-)

**Comment by otavio** [comment]
Unsure. Here it shows a different path for 035.SDM. I suspect you are using Windows?

**Comment by sonnenscheinchen** [comment]
> Here it shows a different path for 035.SDM. 

Where ever this comes from, it's not correct. 
I checked with the "stings" command from binutils and a hex-editor. They usually don't lie. :-) Definitely single 0x5C (according LHA spec).

> I suspect you are using Windows?

No, I use Arch Linux.

**Comment by otavio** [comment]
On list, it shows fine. On extract it fails.

**Comment by cgzones** [comment]
This seems to be fixed (by accident) with https://github.com/OSSystems/compress-tools-rs/commit/e9637bf6ecdeb8b5d38c896f1923df627f949b9b.

Until a buffer size of `6005` it fails, with a size of `6006` or bigger it works.

Probably a libarchive internal bug? (Although running against libarchive build with ASAN and UBSAN reports no issues.)

**Comment by otavio** [comment]
Please add a CHANGES item mentioning this. We could then cut a release :-)

**Comment by cgzones** [comment]
There seems to be an issue with side effects of `archive_read_data_block()` at https://github.com/OSSystems/compress-tools-rs/blob/c08486c89ad4b9dd6abff1711f71ae2068b3d88c/src/lib.rs#L569, cause commenting out
https://github.com/OSSystems/compress-tools-rs/blob/c08486c89ad4b9dd6abff1711f71ae2068b3d88c/src/lib.rs#L276
produces the correct path (but obviously only NUL data).
